#!/usr/bin/env bash
#
# Build the Debian armhf root filesystem with mmdebstrap.
#
# Debian rather than Buildroot/Yocto because the point of this repo is a glibc
# system you can actually live in: apt, security updates, 60k packages, rustup,
# pip wheels. On 256MB of RAM a bookworm/trixie userspace with systemd idles
# around 45MB, which leaves plenty for the NPU.
#
# Requires: mmdebstrap, and qemu-user-static + binfmt when building on x86.

. "$(dirname "$0")/lib.sh"

need mmdebstrap readelf
elevate "$@"

if [ "$(hostarch_deb)" != "$ROOTFS_ARCH" ]; then
	command -v qemu-arm-static >/dev/null 2>&1 \
		|| die "cross-building $ROOTFS_ARCH needs qemu-user-static (and binfmt-support)"
fi

kver="$(cat "$OUT/kernel.release" 2>/dev/null || true)"
[ -n "$kver" ] || die "build the kernel first (make kernel): no $OUT/kernel.release"
[ -d "$OUT/npu-staging" ] || die "build the npu userspace first (make npu)"

# --- package set ------------------------------------------------------------

pkgs=()
read_list() {
	while read -r line; do
		line="${line%%#*}"; line="$(echo "$line" | tr -d '[:space:]')"
		[ -n "$line" ] && pkgs+=("$line")
	done < "$1"
}
case "$ROOTFS_PROFILE" in
minimal)  read_list "$TOP/rootfs/packages/minimal.list" ;;
standard) read_list "$TOP/rootfs/packages/minimal.list"
          read_list "$TOP/rootfs/packages/standard.list" ;;
dev)      read_list "$TOP/rootfs/packages/minimal.list"
          read_list "$TOP/rootfs/packages/standard.list"
          read_list "$TOP/rootfs/packages/dev.list" ;;
*) die "unknown ROOTFS_PROFILE '$ROOTFS_PROFILE' (minimal|standard|dev)" ;;
esac

log "rootfs: debian $ROOTFS_SUITE/$ROOTFS_ARCH, profile $ROOTFS_PROFILE, ${#pkgs[@]} packages"

rootdir="$OUT/rootfs"
rm -rf "$rootdir"
mkdir -p "$rootdir"

# --- overlay staging --------------------------------------------------------
#
# mmdebstrap hooks run with the target as $1. Assemble everything that has to
# land in the rootfs into one tree first so the hook stays a single copy.

ovl="$OUT/rootfs-overlay"
rm -rf "$ovl"; mkdir -p "$ovl"
tar -C "$TOP/rootfs/overlay" -cf - . | tar -C "$ovl" -xf -
tar -C "$OUT/npu-staging"   -cf - . | tar -C "$ovl" -xf -

# Kernel modules and the devicetree/kernel the bootloader will read.
#
# The modules go to usr/lib/modules, not lib/modules. Debian is merged-usr, so
# /lib in the rootfs is a symlink to usr/lib, and GNU tar unpacking a plain
# lib/ directory over it deletes the symlink and puts a real directory there --
# taking /lib/systemd, /lib/ld-linux-armhf.so.3 and the rest of userspace out
# of reach without touching a single file. The hook below extracts with
# --keep-directory-symlink so this cannot happen again by accident.
mkdir -p "$ovl/usr/lib/modules" "$ovl/boot"
tar -C "$OUT/modules/lib/modules" -cf - . | tar -C "$ovl/usr/lib/modules" -xf -
cp -f "$OUT/$KERNEL_IMAGE"      "$ovl/boot/$KERNEL_IMAGE"
cp -f "$OUT/$KERNEL_DTS.dtb"    "$ovl/boot/$KERNEL_DTS.dtb"

# extlinux.conf is what U-Boot's standard boot reads. The root= is only known
# once mk-image.sh has created the partition, so ship a template and let
# mk-image.sh render it on every run -- rendering in place would bake the first
# build's PARTUUID into every later image. UBI boots ignore this file and use
# ubi_bootargs from the U-Boot environment instead.
#
# A leading slash in kernel/fdt makes U-Boot resolve the path from the root of
# the filesystem holding extlinux.conf, and here that filesystem is the rootfs
# itself, so both paths need the /boot they live under. Get this wrong and the
# bootflow is found, parsed and then abandoned with "Skipping luckfox for
# failure retrieving kernel"; mk-image.sh resolves them against the rootfs so
# that happens at build time instead.
#
# root is handed over read-only on purpose. systemd-fsck-root.service carries
# ConditionPathIsReadWrite=!/, so booting straight to rw skips the only fsck
# this system ever gets -- on a board whose power is a USB cable someone pulls.
# Read-only lets it run, and systemd-remount-fs then remounts / with the
# options from /etc/fstab (rw,noatime) before anything writes.
mkdir -p "$ovl/boot/extlinux"
cat > "$ovl/boot/extlinux/extlinux.conf.in" <<-EOF
	# Generated by scripts/mk-image.sh from extlinux.conf.in. Edit freely on
	# the running board; U-Boot reads this file directly.
	default luckfox
	timeout 10
	menu title Luckfox Pico Max

	label luckfox
	    menu label Linux $kver
	    kernel /boot/$KERNEL_IMAGE
	    fdt /boot/$KERNEL_DTS.dtb
	    append root=@@ROOT@@ rootwait ro console=ttyS2,115200n8 rk_dma_heap_cma=$RK_DMA_HEAP_SIZE
EOF

cat > "$ovl/etc/os-release.luckfox" <<-EOF
	LUCKFOX_BOARD="$BOARD_DESC"
	LUCKFOX_KERNEL="$kver"
	LUCKFOX_BUILD="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
EOF

# --- customize --------------------------------------------------------------

hookdir="$OUT/rootfs-hooks"
rm -rf "$hookdir"; mkdir -p "$hookdir"

cat > "$hookdir/customize" <<HOOK
#!/bin/sh
set -eu
target="\$1"

# --no-same-owner because the overlay is assembled from a git checkout that
# belongs to whoever cloned it, and tar run by root faithfully reproduces
# those uids in the rootfs. The overlay ships etc/, so /etc itself ends up
# owned by the build user: systemd-tmpfiles then refuses to follow it
# ("Detected unsafe path transition /etc (owned by 1001)") and anything
# that trusts /etc ownership is one bad uid away from breaking.
tar -C "$ovl" -cf - . | tar -C "\$target" --keep-directory-symlink --no-same-owner -xf -

. "$TOP/rootfs/hooks/customize.sh"
HOOK
chmod +x "$hookdir/customize"

export LUCKFOX_HOSTNAME="$ROOTFS_HOSTNAME"
export LUCKFOX_ROOT_PASSWORD="$ROOTFS_ROOT_PASSWORD"
export LUCKFOX_KVER="$kver"

# --- base rootfs ------------------------------------------------------------
#
# mmdebstrap is ~95% of this script's runtime, and almost all of that is
# qemu-user emulating armhf dpkg and maintainer scripts -- the packages
# themselves download in about two seconds. Nothing in that work depends on
# this build: it is a pure function of the suite, the mirror and the package
# list, so cache the result and only pay for it when one of those changes.
#
# eatmydata drops dpkg's fsync calls, which is worth a few percent on the cold
# path and nothing at all on the warm one. It is only used to build the base;
# the tarball that comes out is unaffected.
#
# The package list is sorted into the key so that reordering a .list file is
# not a cache miss. The profile is in the filename rather than only in the hash
# so that the prune below cannot evict a sibling profile's base when both share
# a $DL -- which is exactly what the two image jobs do locally.
#
# The layout of the base is part of the key too, under a name rather than a
# flag list, because a base built before /usr was merged is a different tree
# from one built after and nothing else in the key can tell them apart.
mkdir -p "$DL/rootfs-base"
base_layout=merged-usr
base_key="$( { printf '%s\n' "$ROOTFS_SUITE" "$ROOTFS_ARCH" "$ROOTFS_MIRROR" \
	"$ROOTFS_COMPONENTS" "$ROOTFS_VARIANT" "$base_layout"
	printf '%s\n' "${pkgs[@]}" | LC_ALL=C sort; } | sha256sum | cut -c1-16)"
base_pfx="$ROOTFS_SUITE-$ROOTFS_ARCH-$ROOTFS_PROFILE"
base="$DL/rootfs-base/$base_pfx-$base_key.tar"

# Debian keeps moving under a cache key that cannot see it: the package list is
# unchanged but the packages it resolves to pick up security updates. Age the
# base out so a long-lived branch cannot ship a stale userspace indefinitely.
if [ -s "$base" ] && [ -n "$(find "$base" -mtime "+$ROOTFS_BASE_MAX_AGE_DAYS" -print -quit)" ]; then
	log "base rootfs older than $ROOTFS_BASE_MAX_AGE_DAYS days, rebuilding"
	rm -f "$base"
fi

if [ -s "$base" ]; then
	log "base rootfs: cached ($(du -m "$base" | cut -f1) MiB, ${base_key})"
else
	log "base rootfs: running mmdebstrap (not cached)"
	rm -f "$base.part"
	# mmdebstrap does not merge /usr on its own -- that is what its merged-usr
	# hook is for, and without it a rootfs can come up with /bin, /sbin and
	# /lib as real directories. Debian has not supported that layout since
	# bookworm, and it quietly invalidates the reasoning in the overlay staging
	# above, which counts on /lib being a symlink into usr/lib. In practice
	# trixie's usr-is-merged gets there on its own, so the hook is insurance --
	# the assertion after the unpack is what actually holds the property. Only
	# the cold path needs the hook installed; a cached base already has it
	# applied.
	#
	# This is not what systemd's "System is tainted: unmerged-bin" is about,
	# despite the name. That check (src/core/taint.c) fires when /usr/sbin is
	# not a symlink to /usr/bin -- the sbin merge, DEP17 -- which Debian has
	# not done as of trixie and no hook here should do behind dpkg's back.
	# Expect that taint on every boot until Debian finishes the transition.
	usrmerge=/usr/share/mmdebstrap/hooks/merged-usr
	[ -d "$usrmerge" ] || die "mmdebstrap has no merged-usr hook at $usrmerge"
	# --format is explicit because the output name has to be a temporary one:
	# mmdebstrap picks directory vs tar from the extension, and a half-written
	# .tar left behind by a cancelled job would be indistinguishable from a
	# complete one on the next run.
	mmdebstrap \
		--arch="$ROOTFS_ARCH" \
		--variant="$ROOTFS_VARIANT" \
		--include="$(IFS=,; echo "${pkgs[*]}")" \
		--components="$ROOTFS_COMPONENTS" \
		--hook-dir="$usrmerge" \
		--hook-dir=/usr/share/mmdebstrap/hooks/eatmydata \
		--format=tar \
		"$ROOTFS_SUITE" "$base.part" "$ROOTFS_MIRROR"
	mv "$base.part" "$base"
	# One base per suite/arch/profile is enough. Without this the cache grows
	# by another 200MB every time someone edits a package list.
	find "$DL/rootfs-base" -maxdepth 1 -type f \
		-name "$base_pfx-*.tar" ! -name "${base##*/}" -delete
fi

# --numeric-owner because the uids in the tarball are the target's, and the
# build host's /etc/passwd has nothing to do with them.
log "unpacking base rootfs"
tar -C "$rootdir" --numeric-owner --exclude='./dev/*' -xf "$base"

# /dev is split out because those entries are device nodes and mknod needs
# CAP_MKNOD, which a container often does not have. Unlike the rest of the
# tree this is not worth failing over: the tar format carries the nodes even
# where the filesystem cannot, mmdebstrap writing a directory silently dropped
# them on exactly the same hosts, and the kernel mounts devtmpfs over /dev
# before init runs -- CONFIG_DEVTMPFS_MOUNT is one of the symbols the config
# check holds -- so the image boots either way.
if ! tar -C "$rootdir" --numeric-owner --wildcards -xf "$base" './dev/*' 2>/dev/null; then
	warn "no static /dev nodes (host cannot mknod); devtmpfs will populate /dev at boot"
fi

# The hook is silent when it decides it has nothing to do, and a cached base
# was built by some earlier run of this script, so check the unpacked tree
# rather than mmdebstrap's exit status.
for d in bin sbin lib; do
	[ -L "$rootdir/$d" ] || die "rootfs: /$d is not a symlink; /usr was not merged"
done

# Everything above is shared between builds; everything below is this build.
"$hookdir/customize" "$rootdir"

# systemd-tmpfiles runs on every boot and owns some of /etc. Debian's
# debian.conf has three L+ lines, and L+ means "delete whatever is there and
# put a symlink here", so a file this overlay ships at one of those paths lives
# exactly as long as it takes systemd-tmpfiles-setup.service to start. That is
# how /etc/default/locale was lost: the overlay shipped a real file, tmpfiles
# replaced it with a symlink to /etc/locale.conf, which nothing shipped, and
# every login logged "pam_env(login:session): Unable to open env file". A file
# that is deleted before userspace reads it is the worst kind of wrong, because
# the build, the image and the git tree all look correct.
while read -r path target; do
	src="$ovl$path"
	[ -e "$src" ] || [ -L "$src" ] || continue
	if [ ! -L "$src" ]; then
		die "rootfs: the overlay ships $path, but tmpfiles.d replaces it with a symlink to $target on every boot; ship $target instead"
	fi
	# Shipping the symlink is fine, but only if it agrees with tmpfiles:
	# otherwise tmpfiles silently wins on the first boot and the build is
	# describing a rootfs that never exists.
	have="$(readlink "$src")"
	[ "$have" = "$target" ] \
		|| die "rootfs: the overlay points $path at $have, tmpfiles.d points it at $target"
done < <(cat "$rootdir"/usr/lib/tmpfiles.d/*.conf "$rootdir"/etc/tmpfiles.d/*.conf 2>/dev/null \
	| awk '$1 ~ /^L\+?$/ && $2 ~ /^\/etc\// { print $2, ($7 == "" ? "-" : $7) }')

# The symlink resolving is a separate claim from the symlink being right, and
# it is the one that actually failed.
locale="$(readlink -f -- "$rootdir/etc/default/locale" 2>/dev/null || true)"
case "$locale" in
"$rootdir"/*) [ -s "$locale" ] || die "rootfs: /etc/default/locale resolves to ${locale#$rootdir}, which is empty or missing" ;;
*)            die "rootfs: /etc/default/locale does not resolve inside the rootfs" ;;
esac
grep -q '^LANG=' "$locale" || die "rootfs: ${locale#$rootdir} sets no LANG"

# The kernel's verdict on a rootfs is one line long -- "No working init found"
# -- and by then it has cost a card write and a reboot, so resolve init here.
#
# Both halves matter. The symlink chain is the obvious one; the ELF
# interpreter is the one that bites, because every dynamically linked binary
# in an armhf rootfs asks for /lib/ld-linux-armhf.so.3 by that exact path. Lose
# the merged-usr /lib -> usr/lib symlink and the loader goes with it: execve
# fails for init, for /bin/sh, for everything the kernel tries, while each
# individual file is still sitting there intact.
init="$(readlink -f -- "$rootdir/sbin/init" 2>/dev/null || true)"
case "$init" in
"$rootdir"/*) [ -x "$init" ] || die "rootfs: /sbin/init resolves to ${init#$rootdir}, which is not executable" ;;
"")           die "rootfs: /sbin/init does not resolve to anything" ;;
*)            die "rootfs: /sbin/init resolves outside the rootfs ($init)" ;;
esac

interp="$(readelf -p .interp "$init" 2>/dev/null | awk '$0 ~ /\// {print $NF; exit}')"
[ -n "$interp" ] || die "rootfs: cannot read the ELF interpreter of ${init#$rootdir}"
[ -e "$rootdir$interp" ] \
	|| die "rootfs: ${init#$rootdir} needs $interp, which is not in the rootfs"
log "init: ${init#$rootdir} via $interp"

size="$(du -sm "$rootdir" | cut -f1)"
log "rootfs built: ${size} MiB at $rootdir"
echo "$size" > "$OUT/rootfs.size-mib"
give_back "$OUT/rootfs.size-mib"
