#!/usr/bin/env bash
#
# Build the Debian armhf root filesystem with mmdebstrap.
#
# Debian rather than Buildroot/Yocto because the point of this repo is a glibc
# system you can actually live in: apt, security updates, 60k packages, rustup,
# pip wheels. On 256MB of RAM a bookworm/trixie userspace with systemd idles
# around 45MB, which leaves plenty for the NPU.
#
# Requires: mmdebstrap, and qemu-user-static + binfmt when building on x86.

. "$(dirname "$0")/lib.sh"

need mmdebstrap
elevate "$@"

if [ "$(hostarch_deb)" != "$ROOTFS_ARCH" ]; then
	command -v qemu-arm-static >/dev/null 2>&1 \
		|| die "cross-building $ROOTFS_ARCH needs qemu-user-static (and binfmt-support)"
fi

kver="$(cat "$OUT/kernel.release" 2>/dev/null || true)"
[ -n "$kver" ] || die "build the kernel first (make kernel): no $OUT/kernel.release"
[ -d "$OUT/npu-staging" ] || die "build the npu userspace first (make npu)"

# --- package set ------------------------------------------------------------

pkgs=()
read_list() {
	while read -r line; do
		line="${line%%#*}"; line="$(echo "$line" | tr -d '[:space:]')"
		[ -n "$line" ] && pkgs+=("$line")
	done < "$1"
}
case "$ROOTFS_PROFILE" in
minimal)  read_list "$TOP/rootfs/packages/minimal.list" ;;
standard) read_list "$TOP/rootfs/packages/minimal.list"
          read_list "$TOP/rootfs/packages/standard.list" ;;
dev)      read_list "$TOP/rootfs/packages/minimal.list"
          read_list "$TOP/rootfs/packages/standard.list"
          read_list "$TOP/rootfs/packages/dev.list" ;;
*) die "unknown ROOTFS_PROFILE '$ROOTFS_PROFILE' (minimal|standard|dev)" ;;
esac

log "rootfs: debian $ROOTFS_SUITE/$ROOTFS_ARCH, profile $ROOTFS_PROFILE, ${#pkgs[@]} packages"

rootdir="$OUT/rootfs"
rm -rf "$rootdir"
mkdir -p "$rootdir"

# --- overlay staging --------------------------------------------------------
#
# mmdebstrap hooks run with the target as $1. Assemble everything that has to
# land in the rootfs into one tree first so the hook stays a single copy.

ovl="$OUT/rootfs-overlay"
rm -rf "$ovl"; mkdir -p "$ovl"
tar -C "$TOP/rootfs/overlay" -cf - . | tar -C "$ovl" -xf -
tar -C "$OUT/npu-staging"   -cf - . | tar -C "$ovl" -xf -

# Kernel modules and the devicetree/kernel the bootloader will read.
mkdir -p "$ovl/lib/modules" "$ovl/boot"
tar -C "$OUT/modules/lib/modules" -cf - . | tar -C "$ovl/lib/modules" -xf -
cp -f "$OUT/$KERNEL_IMAGE"      "$ovl/boot/$KERNEL_IMAGE"
cp -f "$OUT/$KERNEL_DTS.dtb"    "$ovl/boot/$KERNEL_DTS.dtb"

# extlinux.conf is what U-Boot's standard boot reads. The root= is only known
# once mk-image.sh has created the partition, so ship a template and let
# mk-image.sh render it on every run -- rendering in place would bake the first
# build's PARTUUID into every later image. UBI boots ignore this file and use
# ubi_bootargs from the U-Boot environment instead.
mkdir -p "$ovl/boot/extlinux"
cat > "$ovl/boot/extlinux/extlinux.conf.in" <<-EOF
	# Generated by scripts/mk-image.sh from extlinux.conf.in. Edit freely on
	# the running board; U-Boot reads this file directly.
	default luckfox
	timeout 10
	menu title Luckfox Pico Max

	label luckfox
	    menu label Linux $kver
	    kernel /$KERNEL_IMAGE
	    fdt /$KERNEL_DTS.dtb
	    append root=@@ROOT@@ rootwait rw console=ttyS2,115200n8 cma=$CMA_SIZE
EOF

cat > "$ovl/etc/os-release.luckfox" <<-EOF
	LUCKFOX_BOARD="$BOARD_DESC"
	LUCKFOX_KERNEL="$kver"
	LUCKFOX_BUILD="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
EOF

# --- hooks ------------------------------------------------------------------

hookdir="$OUT/rootfs-hooks"
rm -rf "$hookdir"; mkdir -p "$hookdir"

cat > "$hookdir/customize" <<HOOK
#!/bin/sh
set -eu
target="\$1"

tar -C "$ovl" -cf - . | tar -C "\$target" -xf -

. "$TOP/rootfs/hooks/customize.sh"
HOOK
chmod +x "$hookdir/customize"

export LUCKFOX_HOSTNAME="$ROOTFS_HOSTNAME"
export LUCKFOX_ROOT_PASSWORD="$ROOTFS_ROOT_PASSWORD"
export LUCKFOX_KVER="$kver"

log "running mmdebstrap"
mmdebstrap \
	--arch="$ROOTFS_ARCH" \
	--variant=important \
	--include="$(IFS=,; echo "${pkgs[*]}")" \
	--components=main,contrib,non-free-firmware \
	--customize-hook="$hookdir/customize \$1" \
	"$ROOTFS_SUITE" "$rootdir" "$ROOTFS_MIRROR"

size="$(du -sm "$rootdir" | cut -f1)"
log "rootfs built: ${size} MiB at $rootdir"
echo "$size" > "$OUT/rootfs.size-mib"
give_back "$OUT/rootfs.size-mib"
